const testInput = [
  "vJrwpWtwJgWrhcsFMMfFFhFp",
  "jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL",
  "PmmdzqPrVvPwwTWBwg",
  "wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn",
  "ttgJtRGJQctTZtZT",
  "CrZsJsPPZsGzwwsLwLmpwMDw",
];
const rawInput = [
  "hqBqJsqHhHvhHHqlBvlfpHQQwLVzVwtVzjzttjQVSjMjwL",
  "gRTRnCRsFNGbTzLjwcSTMmSz",
  "dGgsRWPGdWgZJqBBqhfpPq",
  "HNCNJHCWJRRLqNJWlfrrrwsmlwGmmf",
  "dddvLdLjdDvjvswlmGwlZQtjrt",
  "dvcpbLVcvNJJHNPHSp",
  "QDprSpLQRLQrQDmQcQFZjbbhZwdRsRFbbBss",
  "gWGGPgNvJlgJzDlNGHCGPNZZgFBbsjbFFBwZwfhdZbZB",
  "lHTlGMHlGCPNvClzGzJHvGcrMcVtLqMLcrrQVcVDrqrm",
  "SrBpJFfldlFNslFJBZwsmwgVGGsCCVmZZD",
  "jLtjvzLQMtWjbbQvDZZwGRJGgwggGZgv",
  "MzqqjznQPqnnjznnctnFlSddPfHflhfBJFNdHd",
  "mPNNGVCRngnSbgNw",
  "WqsqlTssgvqvZWZzhsTzWhScdHtfJJnfbtSJwfczdtSS",
  "sqTvhpqQvWZQLmDpDGMDGrgL",
  "DQRcLQVLbbcbrFPcRtTBBBJnTZrrnmZTrMgJ",
  "slGjjjdlhMfvdMQTvg",
  "jlzNhWHhhWjHlwwwGLDSDtPQVtRzRbSzpp",
  "DzDgfvzfDczfHCHSlgHLCmWG",
  "PrpNPJtpPMBssmmVdmSVVr",
  "PSRMwPnMpBNtNBTnnZwDqzQFfwhjZZqfhh",
  "fzfBwhBJFbCwbwwg",
  "strtgtrPgmPgFRsMdRnZRMFn",
  "mrmLPDvGmmtSLDgmSqvHchhcHQzcQQJHBfBh",
  "NsgwPPDgsPHqsTqqmLbLrDRhmrRVrbVW",
  "lFpGFtfFlvSFplGFzptSGSSlhZbhjhfrmWbhLhmLbCZVZjWr",
  "ccplJQSGcSSpVFvNqqsqPNqPQPTwqd",
  "HFhPNNZGqSZrCDBVZBCB",
  "RJTtwczTzCRVQrRHpR",
  "mfgblfltwgwwmlJgcHNnGhSbFNnFsFjFqG",
  "tSRqNRHpHnMSTqpcmrWWfqfmrCQCrW",
  "lhGDtbgVVgDsDbhfldfwrzrfcdzwcr",
  "vtDDhsgFBTNZFBHS",
  "LcNpLLBNgdmHGmsBCrRBQDDwnwRj",
  "hSWfZVhfPJJhfVWbhzbnQqQnRRRqPvCCrjvjwj",
  "ztJSSJhzzSTJrZSbzzJTfzbZmLmggdmNMFNpmtmMGFFGNpmt",
  "TRdFfLbTnLvZVlZvznQV",
  "pgJGprJNhghhNjjPgPNrhNqqlVVlQVVQqQjfzBfQvZzB",
  "rmGmSwJPwJprrNDbsfMRsdTDcDWHfM",
  "QMpZZTtwMBttJMMbVqPpqLqbVlbqqN",
  "rjCFGrdGRwdDHSnqflPVLqqVNllrfl",
  "DHGDRvhvwTZhJWBQ",
  "LcQCCpLQVhrdcFQCJrmmmwDwvDtJJnnw",
  "TsZqqTzMRqZjfsjTTDjsNJnmnStRSHnnSJmnJSNH",
  "sMMZZbDjZFdbVCFphV",
  "FCcdFFGBsdDrbMNSmSdmQR",
  "tVttHVLhvVgfTTtffNSMQRMZSRmMQNmHSb",
  "gngvvwJtVVTvVvvvfwvJThhCzGcnsCjmCDmscPcGCsGsmz",
  "fsnzRNZswZszPRZSLflPpDhlhvgWHmjWvJjh",
  "bVcCqjbdjbcMdBrddrQphvHHmHWlggpWpppqJJ",
  "FBTdFQGrTjLNsNtL",
  "MSWWgMdgdbWbbfdgsPmddgCmSLZvSFvLQvnLrFNZvZFLlLLl",
  "hjpJjGthjRNRptwJJqVBllnvrrlTTQFZqnTZnn",
  "tjDGHwhHHjwjjJGpwjwjjJpwsdgffmbgMsmbDNcMcdmCPdsm",
  "MlDrrgnTDLlCCmCRFgRSCR",
  "HHhbbNQMccQFSNBmmpJNSJ",
  "MwbMbshsswVbHQsbcVMcrtDllTlLqfTGVzLGrTlT",
  "gSFzqQTpmVpQVpLFLrzJJRthlsQBlPsZsBhZst",
  "rwrNDdbHdBhRhZbsjB",
  "vvvMHwHcwGCwwNfMVSrqffWpSfSFzLmT",
  "RNgMgRCCgCfPNfvNgVQmhPVWWjWjLLdLBj",
  "JhJqqqwGDchsBVbdjldmBLmG",
  "schZzDwTJzFTsctHFMtfftgMttpM",
  "GHHWqWFWfWHqbRWsFZFmqZbhNjNDNppNjrjDcQdbpddhjr",
  "wCLCVPfwgVSnPNrQhnDcjcNpDD",
  "TPgLlggJLVwPVVPPwgTwvtSCFmzGGqzGZsGRqWBGfFRFJFRB",
  "LfFLmGTPHBfpHmzBLdZfBfZTbWWttWSDJtWVDJDtSWJzVCCV",
  "RssRRRhrRwQqMQQwnPngQrwvVSjttjJSjSVtWWCWjbVb",
  "hQPnnRnQgNcQqqQQcsZTNTLpdZZfpZFHNpBp",
  "VTCVVnwfFTvFmTCvWwJHdlhHWBJhJBRWNHgh",
  "ZbSMZbctGtScQSZsSpZpPpplhBhtdJDRDJjhdtlRJRjNRj",
  "rLsbBQSMBGspPGcMPQvnqmwzwmCVLmqVmwTF",
  "GVrrQVHHHQGTllQjPHGrlCQpZZpJFWZFzzjBssDJghzhFZ",
  "NSMmWmtqMWqSNbcctdLcdghpgpppssZgbgzpFzJJFs",
  "cfLqLwMRdtNLMlQrvflWTQPffQ",
  "FjtGflGsbNqjsmjGGGbmqQQQBQBTjdpTpJTWvJBddj",
  "CPrVRMnvvLSRHLnBpwdWTRBQwQzBzR",
  "SnZMZPcHMlqchsvGGb",
  "nnJnswzPCtmZDCpmhphD",
  "rSVVLQQQGQjwpdmdNmpS",
  "VvBcQvGcQgGLBgWrwznfJsncltJsJnssPM",
  "dhbwLStzSGmmmzJJvFgJNvnrgvhv",
  "VTsTsRscRsVBMRVTTsjZVPCnDNvfrPfDvNCfBrPNDJ",
  "scHHQTpJZjHwzLSHHtqHSt",
  "MHmFsBDmGpGTBfmCfWCffhzgvf",
  "wcjwnRLPZRVbtCjtNttGCh",
  "ZLGVJRrnPPPwQwPppqDHFpBFTpqFDr",
  "GzMgVfGRdRVngDjhqcjctrtrzzzs",
  "QbQSHwHSLbWwJJFwJPLPSWTQjrhqtjflThccsclCcscCCmmj",
  "JFbNSbLvHHLQFLvwQJFWSBVgMNGdBBnBMVfddpGngB",
  "sZHNJwMsvHswwvMWqBzhChWPMBzd",
  "bHQQQRDHRcRcDljttBldlPBdggBCqB",
  "QjnDbDjjjncRjbQnfZpvssZNHnppFNpvvp",
  "NdmfPNMHMdNMHcffHBCwwsvsRRllvwlcqjwscw",
  "VLhVGLpLShgvrjwFhjqfls",
  "pppnnQtVpGZVWtzGgVzgSSfnCCDmdPBMDbmmDMmdNMBmWNmm",
  "rrfgCrrMllfnBhBrdCFfWLFmmVFVWQvWwtwV",
  "TmSGSqNzvwwTFVvj",
  "NSGSmNbDzpmSpbHmSJqqlMgdMndcgdccdpgllRRh",
  "bbPtLnLcLJzTjcJbbTcttLcSgwmvWfVvfVvBgfmWVJMJMJMW",
  "ZsDNNGDRsrHzpNRwMlgRlgmMWvffWM",
  "FGzQpZGGLFjnSFbF",
  "DQZVDdWWNBtgWnJCnL",
  "SSHSmbHRFqGrmqJrbbGzjmzCwrvgvwnBwnCvprwvpwwPvv",
  "qFFFSmsRRzzFjcFsSsjmzJzflhlZTTThdhVflZlVDDhMcN",
  "cdvrFddqDtDvqgCDtFtrvvvFSmShPShJVJmMJSJbVBgTlmbM",
  "GzjpHzGHHfQNfJSlPQbJBSTJBM",
  "HWpspsWjNsGRHfpwNszzLfGqnCnZtdvvcZvwqFCcZqMZCv",
  "rhHhDhhDrRNwDRhNRLRqNPHjHSpVpVlljSSMnlHnjS",
  "sVVBsFBJBtBSPSjtjPPZZS",
  "JmddVTzsffcGNwzCqNqR",
  "nQfqFtZWFZnFJWfpGqhDsGLLPLVbrPhr",
  "CzjwMTgBgTNSGLVVDPbjbS",
  "wMCmgNNdgvzGdRQcFGFdfJ",
  "CbqCDnwFpDpCVfBPmPffPfRfpB",
  "svcsjlGJGnlnvjvzgQQgGzsZPhBRcRPhWfBZBhPhWRRhPN",
  "sJngnjSGGTGzgJGrrbCqLHrCLwSFqV",
  "hnRnJrwMHnQRRRwMhRrnJRBLZtBPdPSdtZZjjstsLHBP",
  "pBBzzcbTbzCcFzTvlSCZLCtSvvttdZ",
  "FWmNzBFNDnRqNRDM",
  "lvzlSPRDSpDJmNwNGgFpfsFN",
  "WBHrtrLBbhWHtdrFwFFsjzwfFjsdsF",
  "HWnrHnTWhWTCTzTBnRZqDDDCqZcclRvSJR",
  "qcdVbpcMFQcdMGcMFjjpbCnCGmCnJHDHDGJChzCJCJ",
  "wWwlSfBRgRNBDPJnCgCrgzms",
  "tBTfTRwlwRLNwTRmWtNwQFZtqcjcdcqpbdQMqMdd",
  "jJRzwDdwFdJddcjjFCFvQLvNlBhSBhCC",
  "gMMpbHpmnHpWfnlCSBQCPmPllQSs",
  "nHWHVfTGdTSjZzDT",
  "sCVTsBPltgDSbLvRMMDT",
  "WNrjNmWZwmZwfVLvLRbRNvMp",
  "mrHGrmnjqVzjGqdmCltlhFFllgsHBPCg",
  "wbglgTFRblnMRltJBNrDDWQbtdbN",
  "dqCpcjPLGfHZQBJNGGvQDZ",
  "SPssjVSqPCLpScfCgFRVmTlRwndlRwTR",
  "hWMWMhTTDgWMzGMszQShGWJPCQmPVCNPffPfVJftqNQC",
  "nbnHHwLrnswwPVCPZV",
  "nsRvFHLsvplvrcsSWDDDddjjDlMTjT",
  "HRCnhWZhCddgwRcwhdWZHHQLJzSLsSzjJwSjztsmtzsmLF",
  "VlVVNNVqTlMVbTVVMqvqvrDTjQfFtjstJmzftfzsSbtStJQb",
  "pQvvPpBqNBccPWWhcWWc",
  "glJTndVWCTDDVFvnVndVlCvwmBmqBBwQmwPwmMPggGsPGm",
  "NhcSrhNZHhZzRtHcNRrSMSMSFBMGmsQQGLMPPF",
  "hcpRzbcHjRhRbZRzZRztzRpJVdCdnfCnlFvdDTnJCVDjWd",
  "dqWvjjBdWWqMjdvvMJjWWjMGgcfchhzrhwbrwShwgzSqNb",
  "mmmmsVTlVlsLQmnpsNcfgfwNLgczhcGhzw",
  "RslpsnGGGlWdCZFMMRWR",
  "pfSpZSrdSMVDVVLMMDDZpdgRWMPGqqPGqmqqGGhGHNRN",
  "wwQBwtjvvJlvsnbTbvBRHgPmlqhlqWWHqZZgNm",
  "JnQwJvjTtzTZwJnbzzfCrfLCfdfdddfD",
  "PZcnljZFTVmQdlQh",
  "JCLLqBBCSNCCqzJNzStBpStBmsdhVTdmVWsWmdhfLhWVdfrR",
  "BpMzzqSzppMMqpJqqgzPFcjZjnTjgcjbPjPDPZ",
  "HLHWmqBHHqWbMHFtbgWcdhspPcPchndPpn",
  "ZRVSQZRfVZGRgnfsdhLgLndL",
  "jzJRwJRSJJvSlZQGRVwlSGZDMqmmCCCmtNbCmtCMzFNLbF",
  "fDhlBhhZmQRRfHwLdjHFFWQQjQ",
  "ZMTssVVzvbCqJddsLwwH",
  "TzgTbgGGzztMbbvzvVbGvSPBrlShRrfnNrnBDlNcRDZRZB",
  "bjfqGfvFfcHvRwGFRHjbgQtddlQljWpWnQgdWWll",
  "TSPVVSVwSzSDTDlntDndnlWddt",
  "hTrrNCBCVrCrrVshThHHbZvFGscwbfFGRJcZ",
  "jNhMjcgvMNgWggvttcFtchvPFFzdPPrQrrGGQQszRPQrRG",
  "wSCqCmmppbTwPnGHrQdrGCCD",
  "LlqwGmGScLcVthVt",
  "dGGrWWDqmCnwCCQMQrMbFHbMHsPFgPVZbgFPgg",
  "tLRTBwfvTBJcZFNFZRHSHPVN",
  "zjJLTvjcwDzqqhGD",
  "DzrWszFFrtBBhnhNCClHlnHbSbmlSn",
  "ZLwLcVVZcLVpvRwLgMLpLJgPmmQSNSTNbtTvQmCHQCClCHCt",
  "cfgZJwwVLJZPPVpRwzhzrrfGGBrGtDrBsf",
  "BTsdCQsQnwwdcCqqdCnsFvGFpFBvGzrLLmmzpvfG",
  "pjZjgPVlJVMVtgJSWLPvfFFFbNNmNbvbmL",
  "ggVplgJtHSSggdCHsscChhdnnR",
  "JddZcSlvvGFJNWVWFgQgVtFWhg",
  "nDqsHqCszwjCCPMnfhfBhtdWggfg",
  "bqppHqqHHbPLjLCppbwDdRNvdmcTmlNZGGbTTcNv",
  "lcZDSvztcHHcMSZVHVvMZBqBNNFNhBNTTmssBqBcFB",
  "bbGJQdQPpGfQJQdJfLFhmznhzLLNTFhNhf",
  "JGpWpPJddbPpPwpjbtZSzltDgWDSgvtrVv",
  "lJcNlNjPcmtFzHtHBJFg",
  "VPZdwGGWVrsdPWhWwhzzCzzFppDFMBtttFCr",
  "wshsLVfWTnGswdhwcmRjRmScqTcjlPNq",
  "BsBshRZQQsVdsZQZSdsPDwJDHNNHBztNNFMGGwMF",
  "nSTpLjcvHppzwwNt",
  "jcqncjjvfmgrCfvqrnZbmdmSsdbVWlsmhRdW",
  "FjjqRZjZFZWFqPvNvvPQpmbPDCmt",
  "GSnHSnrScncHhrtncGshVbmTmbpVvppCmpCTmTCmCC",
  "rHfnddwdfctlzFFgwqlj",
  "wBwlBmmhwRVThVBmFHnvHMnfsmFfHq",
  "jzwGSGJNZCCssHfsCPfv",
  "GJbzbZdbwJdtdQphRVWQ",
  "ztFZccVHFWHHLSDBpSBPhhZw",
  "fmjsCmqnNTJnvbTvLRPDlCpBSPBpRShl",
  "JqsGTSNJGqvqvNvttGQQGdFrQctrrF",
  "mNZqjTFrZqrTNTTGSSSbrhrhRFRHcnLCzcCdHcLBdccHLzRC",
  "JDDfJswJDWsvgVgwpWnRBlBzGCnlCLBlcCDl",
  "vVGpfQWJpsPQMVgvppVwgWPJrqSZTrZqhTQTrhjbjqSSjZqt",
  "fMSDzDHzpDDVsStdDgwwFZFrrMPCNngCZP",
  "WmLnbWmvvWTTLWWQWRGQvLvrPFZJcgJFCZNrCgGCFCPNPF",
  "QLhlqhljWvRQbbqlqnfStnHdBqVVfzpq",
  "qWZtSQTSvJJvBfJVBBVFNDNHbbdRVPdpNFRF",
  "fGcwwmCgsLhgwLchbpHdrrrphdPRPh",
  "gMjllmcjwsLMgcwlMnSWzSqjSZJqZqZfjQWv",
  "cdRHPjRFRdFVHGcFfFTHQTHVLSQBsbsqSCLqllBJqqbSqLJC",
  "WwWppWgtNrnzzWDmrrmNvWJClJSSbqLJJCGbsCgJbLLg",
  "MnvWpmwvWnvtGPjVRcHRRHMj",
  "dLMDhdHGrcLTvvvstB",
  "nPqgGGNPqRgRSjgmlWjbbTTPPBvpvpTcswwsTF",
  "NRGmgjRnWgnZJqllmSqjnqSDhQzVrdQHDfDrDJQDMHDJzM",
  "RgmcPmGNQwwNmSRwPPgfmrBlCDlGbvFFvtrCsvlrBB",
  "nfdVnjHdMWnTqflFtbjrllrlsCDl",
  "TZJVMhnfMnVMHnpRRNRzgJRzSzgwPR",
  "nTbsblzlnGllmsNnbDwbcWQWwWBFJBQcWQvPWFJM",
  "HRZRdSRdCdLdRftrHHZfSQBMWJMgMzQPFWMJCFWgvQ",
  "HVzrLrrjRjLGnlTnlDlsjj",
  "RQdTdZhWqlZhTdWTqblhNmTMVnnrQsnnpvgMVMHMgHMrgP",
  "fjSSfjcCzGNBjCjsnpMVpnpzvpzsHp",
  "GGwLGSccwjwLwBcGLGSqZWmmdLZLWThmRNZmWR",
  "ncmBrmfdfcVcfGnQdVWRBRvgqNvDvWqzLRqg",
  "PlpPbSbLFPLpFstsbqRqZMqWZqMWSDRzvq",
  "sjtjHCwJwlHfdfjccmmLLQ",
  "tGMtLHQGWzLHFVQtVfQtMWtbgrZNbdfSbccggrcTjTrfbm",
  "swRChnwqhBCCCmSjcNSdcd",
  "vnlnqDRlsRnJJqswJvGMFVMMdWtpVJFMQQFL",
  "ffcHLzGmfvqqfWfF",
  "rJrrRSPCPMCrPRQMNNWJQjJCnqFVVVTStqVnSBdqppBVtpqd",
  "jNQQPjQMCRQwwQbRQbjMgwbNhwWZHHmzmlchlHHHDcLmWzhD",
  "JzvrRHHJvCRZFPFnPgsQVVQNzQTQDttVsB",
  "GSMjpqdbGNppBtDhPN",
  "MbmqMwGbZPmPHJmv",
  "ggVSVWzCNbbNCbRM",
  "DfVhVsVQcQDmpmQTTQLjPjMjbDGNlbRMlNGG",
  "sftTFJJccnphcfncTsfBvwZvrzgzZzZvBrVnzq",
  "qqlClBNSCNSRQMvdrwFvnBrr",
  "GDfhDtszhhsThpTDzsfpprMrFvQvrnnfvQrwHFbfFH",
  "VtggWhpsmGVTGJWMjWjNjPWjLL",
  "NSnShnjsswSsRPNsrnwcwMHfFwGqbvqCbFfg",
  "LDJtzzmgVVlvqGbzvFfzff",
  "mlJmQQpmJpZpBJJdjBNhrnnRdTTgNN",
  "RtRRvbhDFPHHlhtPhRvPRtqjmzqzzwLjHQHLLLQVmVjq",
  "WNNBBZfgfWnqVQwNqzmQcm",
  "MZGfzSrTTnWrrWsTWnfSGbGllPCbGlJRvlPllCtt",
  "phgcNfqgfpZsjjpdsS",
  "brHHnWPbDPDbTPlDJJvJJPrMVVzRSdFzwdZZzFnsdzzVdVZs",
  "SbStvJMDQgNmmtgg",
  "lzDMDhfFRlfMFTfMGPMbFTlMpBHrmpjjCFjmBmrqBjtCmjjq",
  "VvVswLLHZnJJwdndNsSSNBpCpjqjmNgrmCNtmmqm",
  "nHcZWcSVsScTDlPPlTPb",
  "DFMQSlMDpSpFDtDFccHvmqzvbHZjJmvzmmQH",
  "CSgffrPssdgqRbqzzRqZ",
  "dsdsfGsrBPsTVcMctMVNNhtStW",
  "MDWRDWpgDvWpNptvNMnJCHJHMwHCndJfZn",
  "blcrqTFmmcbhLTTTmlBZbjBJdBfBnCbQBdfn",
  "TzlnhcnzTmhLRvSDsRzDPzWR",
  "nwmmPnnPDjclhhjfFzzzwqbFFNHwVqVq",
  "vSQrbpWCvMWQQWQMLgFJVHqzBzJVNqzBFL",
  "CvCvQtWWQmcbtntPcb",
  "qzvtzCCtLsLLzmQCHqpSsHSmfrnNrTrNWWMNGnWZTMZGBvWn",
  "PglVFJwPhbcghVTBpBnWWhWnTMhB",
  "FgjcJccVpwDcwFgVDsqzddqLqSDSCQQL",
  "PLHsSVGGPvSLTffjMJWJJBjfBL",
  "gNhwgTqDcqwpDqNhFpDFhFWfnndjcMJjMWzzBtntJBnW",
  "DFhhQRRwbCbwRQChppmTHCVGTlslrsvrrSVZ",
  "hHnRfSMmsSVrFvQqrmDPgr",
  "jjcBzjZLpWccJLczBjZjWGwCnNzDvrgPCgQvFggvqrQFnr",
  "jtZGpLwjWBpBWcfMTttfbHRnHTbT",
  "swSHffFTVrJlHFSWrTpMZMPhMNBqBhTvhhqZ",
  "bQbLQGGjQLdRCcQjGZBzpzBZqMBBBVdBqh",
  "RjQDQGmgmVVbVcjjmjgcnWtJfrwsfrtHlwswnfHSFw",
  "bVHbbMFDcbDbcmbbHVRbMRFgzSmdzSSTBtTjBdQTzlSldQjT",
  "nqpqCMwJffqQSzTBQlqd",
  "wvJhnnfrfsJrCNffvspRrPPFMbPMRRPPMZgZHR",
  "FnJZnssHvMdJWJpW",
  "mlDlllGrSGmttwlGvZgrzZNWgggzTzdT",
  "bCltZCthtRcbcFbjFL",
  "JGmHrJwGzzpllRZdzZLRcW",
  "htbPSbVtFbbgjhffgPSfTVSDcHDDDLWscRdsZjdZcRssWc",
  "vhfFbFvVHbtTVgFPhmJBCvBNrqBBrGCqQB",
  "BcNQcvcBchSQNccLLvhTqbJZTrHrrrzzqTZMZMFZ",
  "tpHDsnDRslllCCHtwnpsfjRgrJrVMfMmMrFrzVJFzrVZbZrr",
  "tnDpjCwPLNSPdhPH",
  "qnjvvBwBhSSFPgDQLVVDqgLr",
  "WbszTbHTbsbHJWHLLMVZmJPQDrvmZL",
  "ctlRbtCWWtvlSfjljjhBnBNB",
  "TsnvssDDQlRbzMzjDMqHwq",
  "tSGjZCfFZtCFLtVGWGZFbcqwHbhWdbzbwHbdwbdw",
  "ZGBFJFZVBLjStZPBBZLRvlmsPTvsgrrnrTllvs",
  "PgQdNsQFsdNwWqQBsQrTrTLpbrnTpGngnbTG",
  "hCzzMJVDmfzmBDMCfSfhTMGcnpnTcjGrpjbMGjbL",
  "CVVfvCflSHNHvPdBHW",
  "DwlMjMNjStgmthMghg",
  "PTlpHnJJTcZvTTbHZWZTvpqdHhmLgrgdfrhLLsmshmsLts",
  "vncqTbPqcpCnbCPvccZbDBCGzzNBwjDlVVGFjjVR",
  "QsdGGCztZVRddPgndf",
  "DrNNBbwNHNwlbjFbbCNjNwDWWDPPVfDMgfmVMfnMWmmP",
  "rvJBbbBNcLCtJZQL",
  "NfLlqLhbNPddLPqLhpgHwFFwFHHTwRHWwPFTrT",
  "MSMSCnjBnBjCscjVDVljTvHmmWnrwTrwFTrvTWTT",
  "JCMMBzDMJcZZCjDzSBDNJgdfdQlqlLNdhgGLhp",
];

const day03 = () => {
  const exercise1 = (rucksacks: string[]) => {
    const values = rucksacks.map((rucksack) => {
      const middleIndex = Math.ceil(rucksack.length / 2);
      const firstCompartment = rucksack.slice(0, middleIndex).split("");
      const secondCompartment = rucksack.slice(-middleIndex).split("");
      const duplicates = firstCompartment.filter((item) => {
        const duplicateItems = secondCompartment.filter(
          (item2) => item === item2
        );
        return duplicateItems?.length > 0 && duplicateItems;
      });
      const reduced = duplicates.filter((c, index) => {
        return duplicates.indexOf(c) === index;
      });
      let value = reduced.map((currentValue) => {
        if (currentValue === currentValue.toLowerCase()) {
          return currentValue.charCodeAt(0) - 97 + 1;
        } else {
          return currentValue.charCodeAt(0) - 65 + 27;
        }
      });
      return value.reduce((a, b) => a + b);
    });
    return values.reduce((a, b) => a + b);
  };

  const exercise2 = (rucksacks: string[]) => {
    const groupSize = 3;
    const groups: any = [];
    for (let i = 0; i < rucksacks.length; i += groupSize) {
      groups.push(rucksacks.slice(i, i + groupSize));
    }

    const badges = groups.map((group: string[]) => {
      return group[0]
        .split("")
        .filter(
          (item: any) => group[1]?.includes(item) && group[2]?.includes(item)
        )[0];
    });

    let value = badges.map((currentValue: string) => {
      if (currentValue === currentValue.toLowerCase()) {
        return currentValue.charCodeAt(0) - 97 + 1;
      } else {
        return currentValue.charCodeAt(0) - 65 + 27;
      }
    });
    return value.reduce((a: number, b: number) => a + b);
  };

  console.log("e1", exercise1(rawInput));
  console.log("e2", exercise2(rawInput));
};

export default day03;
